AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 compute stack for aws_ecommerce (single Docker host on Free Tier)

Parameters:
  ProjectName:
    Type: String
    Default: aws-ecommerce
    Description: Project name prefix used for tagging and cross-stack exports.

  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
    Description: EC2 instance type. t3.micro is Free Tier-eligible in this region/account.

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access.

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64
    Description: SSM parameter for the latest Amazon Linux 2023 AMI ID (x86_64).

Resources:
  Ec2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        # Allow SSM Session Manager and basic instance management.
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: ParameterStoreRead
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ProjectName}/*
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-ec2-role"

  Ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref Ec2Role

  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref Ec2InstanceProfile
      KeyName: !Ref KeyName
      SubnetId:
        Fn::ImportValue: !Sub "${ProjectName}-PublicSubnetId"
      SecurityGroupIds:
        - Fn::ImportValue: !Sub "${ProjectName}-InstanceSecurityGroupId"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-app-ec2"
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash
            set -euxo pipefail

            # Update and install basic tooling
            dnf update -y || yum update -y
            dnf install -y docker git || yum install -y docker git

            systemctl enable docker
            systemctl start docker

            # Install docker compose v2 (standalone binary)
            curl -L "https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

            # Add ec2-user to docker group for convenience
            usermod -aG docker ec2-user || true

            echo "Bootstrap complete" > /var/log/aws-ecommerce-bootstrap.log

Outputs:
  InstanceId:
    Description: ID of the EC2 instance running Docker
    Value: !Ref AppInstance

  InstancePublicIp:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt AppInstance.PublicIp

  InstancePublicDnsName:
    Description: Public DNS name of the EC2 instance
    Value: !GetAtt AppInstance.PublicDnsName
